# Generated by Django 2.0 on 2017-07-18 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='articles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='test', max_length=32)),
                ('date', models.DateTimeField(verbose_name='Posted in ')),
                ('type', models.CharField(default='随笔', max_length=20)),
                ('comments_count', models.IntegerField(default=0)),
                ('context', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Posted in ')),
                ('context', models.TextField()),
                ('comment_for', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='default.articles')),
            ],
        ),
        migrations.CreateModel(
            name='link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('friend_blog', '友情博客'), ('friend_link', '友情链接'), ('knowledge_library', '知识库')], max_length=20)),
                ('name', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('passwd', models.CharField(max_length=30)),
                ('article_count', models.IntegerField(default=0)),
                ('birthday', models.DateTimeField(verbose_name='生日 ')),
                ('sex', models.BooleanField(choices=[('man', '男'), ('woman', '女')])),
                ('tel', models.CharField(max_length=11, null=True)),
                ('person_site', models.CharField(max_length=20, null=True)),
                ('signature', models.TextField(max_length=60, null=True)),
                ('about_me', models.TextField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='comments',
            name='username',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='default.users'),
        ),
        migrations.AddField(
            model_name='articles',
            name='auth',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='default.users'),
        ),
    ]
