# Generated by Django 2.0 on 2017-07-19 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('default', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='register_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='birthday',
            field=models.DateTimeField(null=True, verbose_name='生日 '),
        ),
    ]
