# Generated by Django 2.0 on 2017-07-20 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('default', '0002_auto_20170719_0457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='sex',
            field=models.BooleanField(choices=[('True', '男'), ('False', '女')]),
        ),
    ]
