# Generated by Django 2.0 on 2017-07-20 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('default', '0004_auto_20170720_0301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='sex',
            field=models.BooleanField(choices=[('True', '男'), ('False', '女')]),
        ),
    ]
