# Generated by Django 2.0 on 2017-07-21 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('default', '0006_auto_20170721_0622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='sex',
            field=models.BooleanField(choices=[(True, '男'), (False, '女')]),
        ),
    ]
