# Generated by Django 2.0 on 2017-07-23 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('default', '0007_auto_20170721_0624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='date',
            field=models.DateTimeField(auto_now=True, verbose_name='Posted in '),
        ),
        migrations.AlterField(
            model_name='comments',
            name='date',
            field=models.DateTimeField(auto_now=True, verbose_name='Posted in '),
        ),
    ]
