# Generated by Django 2.0 on 2017-07-31 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('default', '0009_auto_20170723_0914'),
    ]

    operations = [
        migrations.CreateModel(
            name='lable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='users',
            name='article_count',
            field=models.IntegerField(default=0, verbose_name='文章数'),
        ),
        migrations.AlterField(
            model_name='users',
            name='person_site',
            field=models.CharField(max_length=20, null=True, verbose_name='个人站点'),
        ),
        migrations.AlterField(
            model_name='users',
            name='register_date',
            field=models.DateTimeField(auto_now=True, verbose_name='注册日期'),
        ),
        migrations.AlterField(
            model_name='users',
            name='tel',
            field=models.CharField(max_length=11, null=True, verbose_name='手机号'),
        ),
    ]
